import { Analytics } from "@vercel/analytics/react"
import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html
      lang="en"
    >
      <Head>
        {/* <title>Create Next App</title> */}
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link
          href="/favicon.ico"
          rel="icon"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
        <Analytics />

      </body>
    </Html>
  );
}
